### PR TITLE
allow 'average' with GDAL v2.0+

### PR DESCRIPTION
**Pull request by MagicForrest**
Simple check to allow the 'average' resample method with GDAL v2.  Currently code only allows 'average' with GDAL > 1.10, even though it seems to be available in in the GDAL v2 from v2.0.

### CODE REVIEW

**Comment by fdetsch** [comment]
Thanks for pointing this out! Since 'master' represents the current **MODIS** version on CRAN, the commit has been merged into 'develop' and remains there until the next CRAN release.

**Comment by MagicForrest** [comment]
Happy to help! I like your package a lot.  Why did it get taken down from CRAN?

Oh, and I have a little bit of feedback (I hope that is okay).  I don't understand how to use getSds() and don't know how to specify particular SDSs for runGdal().  I can get what I want by specifying codes like "111" through trial and error, but I think the documentation is a bit sparse.  It would be great if you could extend the documentation in that area.

**Comment by fdetsch** [comment]
Temporary downtime only - it's already back [online](https://cran.r-project.org/web/packages/MODIS/index.html)!

As regards `getSds()` etc., I'll have another look at the documentation. Briefly, each MODIS product comes with a certain inventory of scientific data sets (SDS). For example, there are 12 different SDS layers available in each [MOD13Q1.006](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mod13q1_v006) `.hdf` file (see table Data Layer Characteristics). Now, if you wanted to extract 'NDVI' (1st SDS), 'VI Quality' (3rd SDS), and 'pixel_reliability' (12th SDS) only, then your `runGdal()` call would go like this:

```
runGdal("MOD13Q1", SDSstring = "101000000001", ...) 
```
ie. "1" means *extract SDS layer at this position* and "0" means *do not extract this SDS*.

**Comment by MagicForrest** [comment]
Cool that it is back on CRAN.

And yes, I kind of figured out the sudo-binary SDSstring thing.  But I wasn't sure if it was also possible to use something like c("Percent_Tree_Cover, "Percent_NonVegetated") so select layers, I couldn't get anything like that to work.  I also couldn't get getSds() function to give me anything sensible when I tried to use the 'SDSstring'  argument.  I did look at the MRT manual quickly but I didn't see anything useful.

I am just down the road in Frankfurt, and I know that my Prof (Thomas Hickler) has some collaborations with some Marburg guys (Jörg Bendix and also maybe others), maybe we will end up collaborating some time!

**Comment by fdetsch** [comment]
Unfortunately, this is not possible at this stage. However, we could think about adding a little helper function that lets you achieve that. The required steps could roughly look as follows:

```
hdf = "D:/Data/MODIS_ARC/MODIS/MOD44B.006/2000.03.05/MOD44B.A2000065.h05v13.006.2017081101737.hdf"
sds = getSds(hdf)$SDSnames

nms = c("Percent_Tree_Cover$", "Percent_NonVegetated$")

SDSstring = rep("0", length(sds))
SDSstring[grep(paste(nms, collapse = "|"), sds)] = "1"
SDSstring = paste(SDSstring, collapse = "")
```

> \> SDSstring
> [1] "1010000"

I'm not in Marburg anymore, but still stationed in Frankfurt and had some collaborations with both BIK-F and Joerg's working group in the past. Feel free to get in touch with me if you need anything!

**Pull request merged**
